// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require('dotenv');
var Process = require('process');
var Telegraf = require('telegraf');
var Telegram$BsTelegraf = require('../src/Telegram.bs.js');

console.log('Hello, BuckleScript and Reason!');

Dotenv.config(undefined);

var apiToken = Process.env['TELEGRAM_TOKEN'];

console.log('apiToken', apiToken);

var hashtag = /#[^ ,.]+/;

function save(message) {
	console.log('message', message);
	return /* () */ 0;
}

new Telegraf(apiToken)
	.hears('messages', function(context) {
		console.log('messages' + context);
		console.log('message' + context.update.message);
		context.reply('Heard: ' + Telegram$BsTelegraf.Message.format(context.update.message));
		return /* () */ 0;
	})
	.startPolling();

exports.apiToken = apiToken;
exports.hashtag = hashtag;
exports.save = save;
/*  Not a pure module */
