// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Telegraf = require("telegraf");
var Telegram$BsTelegraf = require("../src/Telegram.bs.js");

console.log("Hello, BuckleScript and Reason!");

(( require('dotenv').config() ));

console.log("apiToken", process.env.TELEGRAM_TOKEN);

function stringify(str) {
  return JSON.stringify(str, null, 2);
}

new Telegraf(process.env.TELEGRAM_TOKEN).hears("hi", (function (context) {
          console.log(JSON.stringify(context.update.message, null, 2));
          context.reply("Heard: " + Telegram$BsTelegraf.Message.format(context.update.message));
          return /* () */0;
        })).startPolling();

exports.stringify = stringify;
/*  Not a pure module */
