// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var User = { };

function format(m) {
  return "[" + (m.date + ("] <" + (m.from.first_name + ("> " + m.text))));
}

var Message = {
  format: format
};

exports.User = User;
exports.Message = Message;
/* No side effect */
