// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Update = { };

var Context = { };

var Bot = { };

exports.Update = Update;
exports.Context = Context;
exports.Bot = Bot;
/* No side effect */
