// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function format(m) {
  return "[" + (m.date + ("] <" + (m.from + ("> " + m.text))));
}

var Message = {
  format: format
};

exports.Message = Message;
/* No side effect */
